%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: TOW.XLSX
%    Worksheet: Sheet1
%
% Auto-generated by MATLAB

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 14);

% Specify sheet and range
opts.Sheet = "Sheet1";
opts.DataRange = "A3:N1109";

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "Var3", "Temp", "Flow", "Turb", "Cond", "DO", "pH", "TSS", "TSSrem", "TN", "TNrem", "DN"];
opts.SelectedVariableNames = ["Temp", "Flow", "Turb", "Cond", "DO", "pH", "TSS", "TSSrem", "TN", "TNrem", "DN"];
opts.VariableTypes = ["char", "char", "char", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var2", "Var3"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var2", "Var3"], "EmptyFieldRule", "auto");

% Import the data
TOW = readtable("TOW.XLSX", opts, "UseExcel", false);

%% Convert to output type
TOW = table2array(TOW);

%% Clear temporary variables
clear opts