set(groot, 'defaultLineLineWidth', 2, ...
    'defaultLegendInterpreter', 'Latex', ...
    'defaultAxesTickLabelInterpreter', 'Latex',...
    'defaultTextInterpreter', 'Latex',...
    'FixedWidthFontName', 'Arial',...
    'defaultLegendFontSize', 10)